### ISSUE TITLE
PSP Go issue - Saves on ef0 won't appear

### ISSUE THREAD

**Issue by Double-0-seven7** [bucanero/apollo-psp#11]
As the title says.
There is also an issue that you cant get the decryption keys from games if you launch them from ef0 as well (even if you have the save on ms0).

**Comment by bucanero** [comment]
I don't have a PSP Go so I haven't been able to test properly. Right now the "Saves" menu is hardcoded to `ms0:/PSP/SAVEDATA` so it will only show saves from `ms0`.

If you select `ef0` under "Settings", that option currently only changes the source for the "Ext Saves" menu. So it will load saves from `ef0:/APOLLO/SAVEDATA/`

If you are willing to do some tests on PSP Go, I can add a feature to load from `ef0:/PSP/SAVEDATA` based on the user settings.

About decryption keys, there are two things to review:
- the key dumper plugin might not support `ef0`; I haven't tested so I don't know. Can you confirm that the key dump plugin creates keys on `ef0:/PSP/SAVEPLAIN/` ?
- Apollo is only reading decryption keys from `ms0`. Again, this was hardcoded but can be adjusted based on the user settings. I can add code to handle it but I'll also need you to test on a PSP Go.

**Comment by bucanero** [comment]
Update about Key dumping plugins ⚠️ 

I have reviewed the source code of SGDeemer and SGKeyDumper:
- SGDeemer is hardcoded to `ms0`, so probably won't dump any keys if you're using `ef0`.
- SGKeyDumper added `ef0` support after version 1.6, so you could try using the latest 1.7 version and test it out: https://github.com/bucanero/psptools/releases/download/20220719/SGKeyDumper.v1.7.zip

Keep in mind if you try SGKeyDumper 1.7, the plugin doesn't create the dump folder so **you need to manually create folder** `ef0:/PSP/GAME/SED/gamekey/` or else the plugin won't save any key.

**Comment by Pik-a-boo** [comment]
I am willing to try a new version with Go support.
I use the internal memory more then the memory card because the card is only limited to 8gb so it will be a great help.

**Comment by bucanero** [comment]
meanwhile, can you test out the SGKeyDumper plugin (1.7) and confirm if it dumps keys to `ef0`?
I need to be sure that Apollo can access keys from the right path `ef0:/PSP/GAME/SED/gamekey/`

**Comment by Pik-a-boo** [comment]
> meanwhile, can you test out the SGKeyDumper plugin (1.7) and confirm if it dumps keys to `ef0`? I need to be sure that Apollo can access keys from the right path `ef0:/PSP/GAME/SED/gamekey/`

Hmm every time I create it it shows up as coorrupted data...
I tried with and without creating it and still it wont save the keys there.
Dunno if I am doing something wrong or not...

**Comment by bucanero** [comment]
ok, thanks checking the key dump plugin 👍 

btw, the "corrupted data" icon is because the folder `GAME/SED/` has no PARAM.SFO or EBOOT.PBP, so the XMB can't recognize anything. But as long as the keys are dumped there, Apollo will be able to access them and use the data to decrypt/encrypt save data.

**Comment by bucanero** [comment]
@Pik-a-boo can you test this build https://github.com/bucanero/apollo-psp/suites/14332684836/artifacts/806681634  ?
(to download you need to be logged in Github)

This version should list saves on `ef0` , just be sure to select `ef0` as "Save Source" under the Settings menu. Then everything else should work, and also decrypting saves should work loading the keys dumped by the 1.7 plugin from `ef0:/PSP/GAME/SED/gamekey/` .

Let me know if everything works with your PSP Go

**Comment by bucanero** [comment]
hey @Pik-a-boo can you test the fix for PSP Go? any feedback?

**Comment by Pik-a-boo** [comment]
> hey @Pik-a-boo can you test the fix for PSP Go? any feedback?

Seems to work but I only tried changing the save data source place to ef0 and that's it.
All the saves seem to show fine.
