### ISSUE TITLE
Monster Hunter Freedom Unite DLC quests

### ISSUE THREAD

**Issue by Darthagnon** [bucanero/apollo-psp#21]
Monster Hunter Freedom Unite/Portable 2nd G had downloadable quests. However, the savegame could only hold around 6 quests at a time, meaning you'd have to connect to the internet to replace quests. 

[FUComplete](https://github.com/FUComplete/Patch) is a game mod project for Freedom Unite that is able to embed all DLC quests into the game by some black magic. Before that, we had to use the [ MHFU Save Tools ](https://forums.ppsspp.org/showthread.php?tid=5476) to download quest files and embed them offline into our savegames.

I was wondering if some function like this could be added to Apollo PSP?

**Comment by Darthagnon** [comment]
There were also a few games that offered bonus content unlocked by connecting via USB to a PS2 or PS3 game, e.g. Daxter to JakX unlocks Daxter's goggles, or AC Bloodlines also had some unlock. Would it be possible to add those unlocks to Apollo PSP, too?

Thank you for making this tool!

**Comment by bucanero** [comment]
At least the custom MH save decrypt/encryption could be handled by Apollo.
About the quests I'd have to check those links and "MHFU Save tools" to understand what they're doing and if it's something doable.

btw, I also found this Python scripts: https://github.com/svanheulen/mhef

**Comment by Darthagnon** [comment]
If the Monster Hunter save tool has any issues, e.g. it was a script that downloaded quest files, so the original server might be 404, I have a backup with all quest files that I can provide if needed.

**Comment by bucanero** [comment]
> If the Monster Hunter save tool has any issues, e.g. it was a script that downloaded quest files, so the original server might be 404, I have a backup with all quest files that I can provide if needed.

yes, that would be great. Can you share a .Zip with all the quest files, to avoid 404s while trying those scripts?

**Comment by Darthagnon** [comment]
[MHFU Save Tools.zip](https://github.com/bucanero/apollo-psp/files/13260821/MHFU.Save.Tools.zip)

**Comment by Darthagnon** [comment]
MHFU EU build, EBOOT, ULES01213 - I can test if you like?

**Comment by bucanero** [comment]
> MHFU EU build, EBOOT, ULES01213 - I can test if you like?

ok, great. 👍 when I have a chance I'll get a new Apollo build with the script files for ULES01213 so you can test out.

**Comment by bucanero** [comment]
@Darthagnon , here's a test build with the Monster hunter patches:
https://www.mediafire.com/file/5bz9vmbflhliw2z/apollo-psp.zip/file

install the app, and try modding the ULES01213 saves. Apollo should show a few codes, to decrypt the save, update checksums, and encrypt again.

The codes also include injecting 2 quests on slots 1 and 2. I'll include all the other quests, once you confirm the injecting works as expected.
(I know the quest limit is 6 slots, so I'll probably add the inject codes but they'll repeat the slots at some point.)

Note: I suggest making a backup of your save or even better, start with a clean save to test things to avoid risk of losing your current MH save data.

**Comment by bucanero** [comment]
@wr0zen has been testing and injected quests show up fine under the "download" menu after modding a save with Apollo.

for reference, here's a repo with a lot of PSP monster Hunter saves with quests and events added: https://github.com/viciousShadow/MH-PSP-DLC

**Comment by bucanero** [comment]
`.savepatch` files with Monster Hunter quests added:
- https://github.com/bucanero/apollo-patches/blob/main/PSP/ULES01213.savepatch
- https://github.com/bucanero/apollo-patches/blob/main/PSP/ULUS10391.savepatch
- https://github.com/bucanero/apollo-patches/blob/main/PSP/ULJM05500.savepatch

This will be available in the next version.

**Comment by Darthagnon** [comment]
How do we add the quests? I was testing, and all I see in the save edit menu is 
```
Quest Slot #1: mG0010.mib
Quest Slot #2: mG0011.mib
```

Shouldn't there be 6x Quest slots, with a list of `*.mib` files that can be applied to that save slot appearing when each quest slot is selected? A friendly name per `*.mib` would help a lot with figuring out which quest is selected

**Comment by bucanero** [comment]
Download the latest version from the release page. It has all the features and quests there.

**Comment by Darthagnon** [comment]
> Download the latest version from the release page. It has all the features and quests there.

I have updated to the latest release v1.2.0 and can't see any way of changing the quests to add to the MHFU save... :'(

**Comment by bucanero** [comment]
yes, correct, it's not part of the 1.2.0 PSP release, I mixed up with the latest Vita release.

This MHFU hack won't be available until the next PSP release. It might work with the test build I shared before, if you add the `savepatch` files from GitHub.

**Comment by Darthagnon** [comment]
I tried adding the savepatch files to v1.2.0, and added 6x quests, but it corrupted the test save. Will they only work properly with the prerelease build?

**Comment by Darthagnon** [comment]
## Bug
MHFU quest patches also show up as available for MHFU install data.

**Comment by bucanero** [comment]
> MHFU quest patches also show up as available for MHFU install data, which has foldername `ULES01213DAT`.

Not a bug. Patch loading is done by TITLE-ID. The quest codes are still only targeting `MHP2NDG.BIN`, so unless the install data is using the same filename, even if you try it won't modify the file.

In any case, it's the user's responsibility to know when/where/what to patch if they want to apply such changes.
