### ISSUE TITLE
Fake "Install Data"?

### ISSUE THREAD

**Issue by Darthagnon** [bucanero/apollo-psp#22]
Some games on the PSP have "Install Data", which originally was a Memory Stick cache of uncompressed UMD data to speed disk loading times. These days, most people use EBOOTs/ISO/CSO running off the memory stick, so there is no speed bonus for using install data. However, some games lock features behind install data. 

Example 1: Monster Hunter Freedom Unite requires you to press SELECT to view weapon previews in the shop. However, if you have Install Data (500mb), then the previews appear automatically.

Example 2: MGS Peace Walker locks Codec conversations of some sort behind having install data. 

I was wondering if there was a way of generating fake install data, e.g. a stub that is only a few kb in size, but is still recognised as valid install data by the games, thus unlocking the weapon previews, codec calls, etc. without having to waste memory stick space?

I don't know if this would be beyond the scope of the project, but I figured it's worth asking since there seems to be a fair bit of savedata decryption work going on...

**Comment by bucanero** [comment]
this would require specific analysis on each game, but I'm sure that this won't be possible unless you can patch the game binary EBOOT code, it's not just the save-data.
You'll have to patch the game code to skip the save and load the data from the memory stick.

It's the same issue with PS3 backups, you can have an ISO on the HDD, but the game will require to install game data anyways. The only way to avoid such "double install" would be to hack the game EBOOT, and skip that requirement or re-route the way a game loads the files.
