### ISSUE TITLE
[Feature Request] Save game archival

### ISSUE THREAD

**Issue by Darthagnon** [bucanero/apollo-psp#26]
As Apollo is capable of backing up PSP saves, I was wondering if I could request a feature: archival of saves? TL;DR the ability to move saves from the savedata folder and store them elsewhere with a unique identifier, and restore them.

### Use case
Most PSP games are capable of making loads of savegames. So you can have multiple story runs saved simulatenously. However, many also do not differentiate between savegames; there is no player name, and the savegame only presents basic information such as story completion percentage, chapter name, etc. - this makes it easy to accidentally overwrite an old story run. For example, Daxter: I have an old story run with some unique "Pokemons" captured, and a more recent story run with different "Pokemons". I have to be very careful when saving the game to overwrite the correct save, depending on which I'm playing, as the Save Game doesn't give me anything other than 89% game completion, date of last save (changes each time the game is saved) and the game map location. It would help if I was able to put different usernames, e.g. Darthagnon for one savegame, JoeBloggs for another, but the game does not offer this feature. The same applies to a lot of other PSP games, most that give players the system menu to save by. Games that use Monster Hunter-style saving (only 1 savegame allowed, system save menu is never presented to the user), or others that prompt for a player name, don't have this issue.

### Feature request
In a menu listing the current savegames on the PSP, it would be nice if we could go into options for a particular savegame and archive it. What this does is move the save file to, say, `ms0:/PSP/ARCHIVE/GameName_PersistentRandomUniquePhrase/` or `GameName_UserSpecifiedPhrase`. It is no longer present in the SAVEDATA folder, so the game cannot find it. This would allow saving historical runs without having to fiddle with files and folders on a PC or PSP file manager. For example, I could archive my 2012 Daxter run as `ms0:/PSP/ARCHIVE/Daxter_HippoSnake/` or `ms0:/PSP/ARCHIVE/Daxter_Darth2012/` , and now when I save Daxter for my new run, there is no worry of accidentally saving over the old game. 

Restoration of archived games would also be useful, so a list of archived games from which there is the option to restore the savedata could be used. I imagine some additional metadata would also be needed, so that Apollo knows the difference between `Daxter_HippoSnake` from 2012 and `Daxter_WombatHorse` from 2023 and can swap them out accordingly. 

This feature could be even more useful on more recent consoles' versions of Apollo, e.g. PS3, PS Vita and PS4 all tend to have single savegames per game, rather than the multiple used on the PSP, making it impossible to start a clean run without deleting your save (or painstakingly moving it elsewhere with a file manager and remembering that `PCS001234` means Game X).

### Is something like this already possible in Apollo?
Maybe I'm overthinking, or haven't used Apollo enough, but is it possible to do something like this already, with the tools already in Apollo?

**Comment by bucanero** [comment]
This could be added but I'm not planning on working on such feature. 

My suggestion is to use the current "Export to Zip" option in Apollo, as each `.zip` is new and won't overwrite any older zipped save even from the same game. Yes, you'll have to unzip and move the save when you want to use it, but since it's for archival purposes I assume it's a thing that you'll be doing only once in a while.

**Comment by Darthagnon** [comment]
What does "Multi-user: supports multiple user accounts" in the Readme mean? It sounds like the sort of thing that would answer this issue - User 1 has one save game, User 2 another, etc. but afaik PSP is a single-user machine?

**Comment by bucanero** [comment]
> What does "Multi-user: supports multiple user accounts" in the Readme mean? It sounds like the sort of thing that would answer this issue - User 1 has one save game, User 2 another, etc. but afaik PSP is a single-user machine?

oh, that was just a left over from the original Apollo save tool readme from PS3. I have just updated the Readme and removed that reference as it has nothing to do with the PSP version. (on PS3 and PS4 you can have multiple user accounts on the same console, but PSP/Vita only have a single user)

**Comment by Darthagnon** [comment]
Would it be possible to add an option to display the Folder rather than the TitleID in the savedata list? That would help towards this, e.g. currently Apollo displays:
```
Daxter™     UCES00044    PSP
Daxter™     UCES00044    PSP
Final Fantasy Type-0    NPJH50443    PSP
Final Fantasy Type-0    NPJH50443    PSP
Final Fantasy Type-0    NPJH50443    PSP
```
which would be better displayed as:
```
Daxter™     UCES00044DATA00    PSP
Daxter™     UCES00044DATA01    PSP
Final Fantasy Type-0    NPJH50443SYSTEMDATA    PSP
Final Fantasy Type-0    NPJH50443GAMEDATA0    PSP
Final Fantasy Type-0    NPJH50443GAMEDATA1    PSP
```

**Comment by bucanero** [comment]
there's limited screen space, it's impossible to fit folder names. You can still find the full save details by pressing `TRIANGLE` over a save game.
